name: ripseq-rpb4
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Core system
  - r-base=4.4.0

  # Bioinformatics tools
  - fastqc=0.11.9
  - trimmomatic=0.39
  - bowtie2=2.4.4
  - subread=2.0.3
  - samtools=1.13 
  - bedtools=2.30.0
  - macs2=2.2.9.1
